version: '3.7'
services:
  spark-master:
    image: michalklempa/spark
    command: /opt/spark/master.sh
    networks:
      - spark
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 7077
        published: 7077
        protocol: tcp
        mode: host

  spark-worker-1:
    image: michalklempa/spark
    command: /opt/spark/worker.sh
    networks:
      - spark
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host

  spark-worker-2:
    image: michalklempa/spark
    command: /opt/spark/worker.sh
    networks:
      - spark
    ports:
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host

  spark-worker-3:
    image: michalklempa/spark
    command: /opt/spark/worker.sh
    networks:
      - spark
    ports:
      - target: 8080
        published: 8083
        protocol: tcp
        mode: host

#  spark-driver:
#    image: michalklempa/spark
#    command: /opt/spark/submit.sh
#    restart: on-failure
#    networks:
#      - spark
#    ports:
#      - target: 8080
#        published: 8084
#        protocol: tcp
#        mode: host

networks:
  spark:
    external: true
