FROM python:2.7-slim
ENV SPARK_MASTER_HOST=spark-master
ENV SPARK_MASTER_HTTP_PORT=8080

COPY ./spark-ui-proxy.py /

ENV SERVER_PORT=8080
ENV BIND_ADDR="0.0.0.0"

EXPOSE 8080

CMD ["python", "/spark-ui-proxy.py" ]